version: '2'

services:
  app:
    build: .
    container_name: socksApp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Socks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"


  db:
    image: 'postgres:13.3'
    container_name: db
    environment:
      - POSTGRES_DB=Socks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"